name: flutekeyboard
description: "Fully customizable, multi-lanugage virtual keyboard for embedded projects"
version: 0.1.1
repository: https://github.com/amarula/flutekeyboard
homepage: https://github.com/amarula/flutekeyboard

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

topics:
  - keyboard
  - virtual-keyboard
  - widget